name: Generate SVGs

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate AI Futuristic Header SVG
        run: |
          mkdir -p assets
          cat > assets/ai-futuristic.svg <<'EOF'
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="250">
  <defs>
    <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#00f7ff;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#2b86c5;stop-opacity:1" />
    </linearGradient>
  </defs>
  <rect width="100%" height="100%" fill="url(#grad)" />
  <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle"
        style="fill:white;font-family:Fira Code, monospace;font-size:42px;font-weight:bold;">
    Amit Chandra | AI Engineer
  </text>
</svg>
EOF

      - name: Generate Matrix Footer SVG
        run: |
          mkdir -p assets
          cat > assets/matrix-footer.svg <<'EOF'
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100">
  <defs>
    <linearGradient id="matrix" x1="0%" y1="0%" x2="0%" y2="100%">
      <stop offset="0%" style="stop-color:#00ff00;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#003300;stop-opacity:1" />
    </linearGradient>
  </defs>
  <rect width="100%" height="100%" fill="url(#matrix)" />
  <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle"
        style="fill:#0f0;font-family:monospace;font-size:24px;">
    01001101 01100001 01110100 01110010 01101001 01111000
  </text>
</svg>
EOF

      - name: Commit and push SVGs
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/*.svg
          git commit -m "chore: auto-generate AI SVGs" || echo "No changes to commit"
          git push
